---
- name: install packages
  package: name={{ item }}
           update_cache=yes
           state=present
  with_items:
  - curl
  - apt-transport-https


- name: install apt key
  apt_key: url=https://packages.gitlab.com/runner/gitlab-ci-multi-runner/gpgkey
           state=present


- name: download configuration
  get_url: url=https://packages.gitlab.com/install/repositories/runner/gitlab-ci-multi-runner/config_file.list?os=Ubuntu&dist={{ ubuntu_version }}&source=script
           dest=/etc/apt/sources.list.d/runner_gitlab-ci-multi-runner.list
