---
- name: copy debian apt pinning
  template: src=pin-gitlab-runner.pref
            dest=/etc/apt/preferences.d/pin-gitlab-runner.pref
            owner=root
            group=root
            mode=0644
